import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:workiomtest/core/constant/routes.dart';
import 'package:workiomtest/data/datasource/remote/auth/editions_for_select.dart';
import 'package:workiomtest/data/model/getting_editionsmodel.dart';
import 'package:workiomtest/linkapi.dart';

abstract class SignupController extends GetxController {
  goToStrongPassword();
}

class SignupControllerImp extends SignupController {
  late TextEditingController email, password;
  late String editionId;
  bool isShowPass = true;

  // data source
  GetEditionsForSelect getEditionsForSelectData =
      GetEditionsForSelect(Get.find());

  @override
  goToStrongPassword() {
    Get.offNamed(
      AppRoute.signUp_strongPassword,
      arguments: {"editionId": editionId},
    );
  }

  @override
  void onInit() {
    getEditionsForSelect();
    super.onInit();
  }

  // to fetch data for Editions from Api
  getEditionsForSelect() async {
    var response =
        await getEditionsForSelectData.getData(LinkApi.GetEditionsForSelect);
    Autogenerated r;
    r = Autogenerated.fromJson(response);
    editionId = r.result!.editionsWithFeatures![0].edition!.id.toString();
  }

  showPassword() {
    isShowPass = isShowPass == true ? false : true;
    update();
  }

  goToSingIn() {
    Get.toNamed(AppRoute.logIn);
  }
}
